from django.contrib import admin

from .models import ChamberOfCommerce


@admin.register(ChamberOfCommerce)
class ChamberOfCommerceAdmin(admin.ModelAdmin):
    list_display = ('pk', 'name', 'descr', 'created_at', )
    # At least now. Also I excluded autogenerated field.
    exclude = ('id',)

    def save_model(self, request, obj, form, change):
        if not change:
            obj.users.add(request.user)
        return super().save_model(request, obj, form, change)
