# Generated by Django 2.0.13 on 2019-05-07 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dst_country', django_countries.fields.CountryField(max_length=2, verbose_name='Destination country')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete'), ('lodged', 'Lodged'), ('accepted', 'Accepted'), ('error', 'Error')], default='draft', max_length=12)),
                ('exporter_info', models.TextField(blank=True, default='', max_length=10000, verbose_name='Exporter’s name, address and country')),
                ('producer_info', models.TextField(blank=True, default='', max_length=10000, verbose_name='Producer’s name and address')),
                ('importer_info', models.TextField(blank=True, default='', max_length=10000, verbose_name='Importer’s name, address and country')),
                ('transport_info', models.TextField(blank=True, default='', help_text='Departure date, Vessel/Flight/Train/Vehicle No., Port of loading, Port of discharge', max_length=10000, verbose_name='Means of transport and route')),
                ('remarks', models.TextField(blank=True, default='', max_length=8000)),
                ('item_no', models.TextField(blank=True, default='', max_length=8000, verbose_name='Item number (max. 20)')),
                ('packages_marks', models.TextField(blank=True, default='', max_length=8000, verbose_name='Marks and numbers on packages')),
                ('goods_descr', models.TextField(blank=True, default='', max_length=8000, verbose_name='Number and kind of packages; description of goods')),
                ('hs_code', models.CharField(blank=True, default='', max_length=6, verbose_name='HS Code')),
                ('invoice_info', models.CharField(blank=True, default='', max_length=200, verbose_name='Invoice number and date')),
                ('origin_criterion', models.TextField(blank=True, default='', max_length=2000, verbose_name='Origin criterion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisations.ChamberOfCommerce')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CertificateDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='certificate-application-documents')),
                ('type', models.CharField(choices=[('Exporters Information Form Update', 'Exporters Information Form Update'), ('Evidence of origin', 'Evidence of origin'), ('extra', 'Extra document')], max_length=40)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='certificates.Certificate')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
