# Generated by Django 2.0.13 on 2019-06-04 18:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20190604_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='acquitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='acquitted_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, help_text='Acquittal events received'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete'), ('lodged', 'Lodged'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('acquitted', 'Acquitted'), ('error', 'Error')], default='draft', max_length=12),
        ),
    ]
