# Generated by Django 2.0.13 on 2019-06-12 08:41

from django.db import migrations, models
import django_countries.fields


def create_initial_recipients(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    RecipientCountry = apps.get_model('certificates', 'RecipientCountry')
    RecipientCountry.objects.bulk_create([
        RecipientCountry(country='CN', agreement_name='China-Australia Free Trade Agreement'),
        RecipientCountry(country='JP', agreement_name='Japan-Australia Economic Partnership Agreement'),
        RecipientCountry(country='KR', agreement_name='Korea-Australia Free Trade Agreement'),
        RecipientCountry(country='TH', agreement_name='Thailand-Australia Free Trade Agreement'),
        RecipientCountry(country='BN', agreement_name='AANZFTA First Protocol'),
        RecipientCountry(country='MM', agreement_name='AANZFTA First Protocol'),
        RecipientCountry(country='KH', agreement_name='AANZFTA First Protocol'),
        RecipientCountry(country='ID', agreement_name='AANZFTA First Protocol'),
        RecipientCountry(country='LA', agreement_name='AANZFTA First Protocol'),
        RecipientCountry(country='MY', agreement_name='AANZFTA First Protocol'),
        RecipientCountry(country='NZ', agreement_name='AANZFTA First Protocol'),
        RecipientCountry(country='PH', agreement_name='AANZFTA First Protocol'),
        RecipientCountry(country='SG', agreement_name='AANZFTA First Protocol'),
        # Note: Thailang twice
        RecipientCountry(country='TH', agreement_name='AANZFTA First Protocol'),
        RecipientCountry(country='VN', agreement_name='AANZFTA First Protocol'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_auto_20190604_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('agreement_name', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'verbose_name_plural': 'recipient countries',
                'ordering': ('country',),
            },
        ),
        migrations.RunPython(create_initial_recipients, migrations.RunPython.noop),
    ]
