# Generated by Django 2.0.13 on 2019-06-20 08:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_recipientcountry'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='intergov_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Details about communication with the Intergov'),
        ),
    ]
