# Generated by Django 2.2.10 on 2020-05-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_certificate_intergov_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='org',
        ),
        migrations.AlterField(
            model_name='certificatedocument',
            name='type',
            field=models.CharField(choices=[('Exporters Information Form Update', '[Upstream] Exporters Information Form Update, required'), ('Evidence of origin', '[Local] Evidence of origin, optional'), ('extra_int', '[Local] Extra document'), ('extra_upstream', '[Upstream] Extra document')], max_length=40),
        ),
    ]
