# Generated by Django 2.0.13 on 2019-06-09 08:57

from django.db import migrations


def create_dumb_orgs(apps, schema_editor):
    '''
    We can't import the Post model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''
    ChamberOfCommerce = apps.get_model('organisations', 'ChamberOfCommerce')
    ChamberOfCommerce.objects.create(
        name='First Chamber',
        descr='Automatically created on app init'
    )
    ChamberOfCommerce.objects.create(
        name='CustomChamber01',
        descr='Automatically created on app init'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_dumb_orgs, migrations.RunPython.noop),
    ]
