# Generated by Django 2.2.10 on 2020-05-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_auto_20200502_1802'),
        ('organisations', '0002_dumb_org'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChamberOfCommerce',
        ),
    ]
